name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master # or whatever branch you use
  workflow_dispatch: # Allow manual trigger


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # or your desired version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown jinja2

      - name: Generate blog
        run: python generate.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Point to your build directory